apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-pricing-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dynamic-pricing-api
  template:
    metadata:
      labels:
        app: dynamic-pricing-api
    spec:
      containers:
      - name: dynamic-pricing-api
        image: eghosa40/dynamic-pricing-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/dynamic_pricing_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password"

