apiVersion: v1
kind: Service
metadata:
  name: dynamic-pricing-service
spec:
  type: LoadBalancer
  selector:
    app: dynamic-pricing-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
